import { TagsResponse } from "@/types";

export const tagsData: TagsResponse = {
  items: [
    {
      last_activity_date: 1712144823,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2529012,
      name: "javascript",
    },
    {
      last_activity_date: 1712144869,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2192554,
      name: "python",
    },
    {
      last_activity_date: 1712144118,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1917382,
      name: "java",
    },
    {
      last_activity_date: 1712144632,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1615166,
      name: "c#",
    },
    {
      collectives: [
        {
          tags: ["php"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective where developers working with PHP can learn and connect about the open source scripting language.",
          link: "/collectives/php",
          name: "PHP",
          slug: "php",
        },
      ],
      last_activity_date: 1712144823,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1464501,
      name: "php",
    },
    {
      collectives: [
        {
          tags: ["android", "ios"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
          link: "/collectives/mobile-dev",
          name: "Mobile Development",
          slug: "mobile-dev",
        },
      ],
      last_activity_date: 1712142732,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1417283,
      name: "android",
    },
    {
      last_activity_date: 1712144823,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1187378,
      name: "html",
    },
    {
      last_activity_date: 1712142912,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1034799,
      name: "jquery",
    },
    {
      last_activity_date: 1712144265,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 806785,
      name: "c++",
    },
    {
      last_activity_date: 1712144360,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 804261,
      name: "css",
    },
    {
      collectives: [
        {
          tags: ["android", "ios"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
          link: "/collectives/mobile-dev",
          name: "Mobile Development",
          slug: "mobile-dev",
        },
      ],
      last_activity_date: 1712144701,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 687281,
      name: "ios",
    },
    {
      last_activity_date: 1712144167,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 670801,
      name: "sql",
    },
    {
      last_activity_date: 1712137074,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 662023,
      name: "mysql",
    },
    {
      collectives: [
        {
          tags: [
            "stringr",
            "r-raster",
            "r",
            "shinyapps",
            "readr",
            "ggplot2",
            "knitr",
            "r-caret",
            "shinydashboard",
            "quantmod",
            "zoo",
            "tibble",
            "rlang",
            "data.table",
            "dtplyr",
            "forcats",
            "tidyr",
            "plyr",
            "shiny-server",
            "lubridate",
            "shiny",
            "dplyr",
            "purrr",
            "tidyverse",
            "rstudio",
            "rvest",
            "r-package",
          ],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective where data scientists and AI researchers gather to find, share, and learn about R and other subtags like knitr and dplyr.",
          link: "/collectives/r-language",
          name: "R Language",
          slug: "r-language",
        },
      ],
      last_activity_date: 1712144320,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 505676,
      name: "r",
    },
    {
      last_activity_date: 1712144472,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 476785,
      name: "reactjs",
    },
    {
      last_activity_date: 1712144588,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 472039,
      name: "node.js",
    },
    {
      last_activity_date: 1712141477,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 416721,
      name: "arrays",
    },
    {
      last_activity_date: 1712144326,
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 403992,
      name: "c",
    },
    {
      last_activity_date: 1712140514,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 374623,
      name: "asp.net",
    },
    {
      last_activity_date: 1712135038,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 360348,
      name: "json",
    },
    {
      last_activity_date: 1712143371,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 343665,
      name: "python-3.x",
    },
    {
      last_activity_date: 1712143333,
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 338057,
      name: "ruby-on-rails",
    },
  ],
  has_more: true,
  quota_max: 300,
  quota_remaining: 279,
  total: 22,
};
